package tfc;
import java.util.Collection;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;
/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Materia <br>
 * @version generated on Fri Sep 06 19:04:07 CEST 2013 by daniel
 */
public interface Materia extends WrappedIndividual {
    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_constaDe_AS
     */
    /**
     * Gets all property values for the MA_constaDe_AS property.<p>
     * 
     * @returns a collection of values for the MA_constaDe_AS property.
     */
    Collection<? extends Asignatura> getMA_constaDe_AS();
    /**
     * Checks if the class has a MA_constaDe_AS property value.<p>
     * 
     * @return true if there is a MA_constaDe_AS property value.
     */
    boolean hasMA_constaDe_AS();
    /**
     * Adds a MA_constaDe_AS property value.<p>
     * 
     * @param newMA_constaDe_AS the MA_constaDe_AS property value to be added
     */
    void addMA_constaDe_AS(Asignatura newMA_constaDe_AS);
    /**
     * Removes a MA_constaDe_AS property value.<p>
     * 
     * @param oldMA_constaDe_AS the MA_constaDe_AS property value to be removed.
     */
    void removeMA_constaDe_AS(Asignatura oldMA_constaDe_AS);
    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_otorgaCompetenciasEspecificas_CE
     */
    /**
     * Gets all property values for the MA_otorgaCompetenciasEspecificas_CE property.<p>
     * 
     * @returns a collection of values for the MA_otorgaCompetenciasEspecificas_CE property.
     */
    Collection<? extends Competencia_Especifica> getMA_otorgaCompetenciasEspecificas_CE();
    /**
     * Checks if the class has a MA_otorgaCompetenciasEspecificas_CE property value.<p>
     * 
     * @return true if there is a MA_otorgaCompetenciasEspecificas_CE property value.
     */
    boolean hasMA_otorgaCompetenciasEspecificas_CE();
    /**
     * Adds a MA_otorgaCompetenciasEspecificas_CE property value.<p>
     * 
     * @param newMA_otorgaCompetenciasEspecificas_CE the MA_otorgaCompetenciasEspecificas_CE property value to be added
     */
    void addMA_otorgaCompetenciasEspecificas_CE(Competencia_Especifica newMA_otorgaCompetenciasEspecificas_CE);
    /**
     * Removes a MA_otorgaCompetenciasEspecificas_CE property value.<p>
     * 
     * @param oldMA_otorgaCompetenciasEspecificas_CE the MA_otorgaCompetenciasEspecificas_CE property value to be removed.
     */
    void removeMA_otorgaCompetenciasEspecificas_CE(Competencia_Especifica oldMA_otorgaCompetenciasEspecificas_CE);
    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_otorgaCompetenciasGenerales_CG
     */
    /**
     * Gets all property values for the MA_otorgaCompetenciasGenerales_CG property.<p>
     * 
     * @returns a collection of values for the MA_otorgaCompetenciasGenerales_CG property.
     */
    Collection<? extends Competencia_General> getMA_otorgaCompetenciasGenerales_CG();
    /**
     * Checks if the class has a MA_otorgaCompetenciasGenerales_CG property value.<p>
     * 
     * @return true if there is a MA_otorgaCompetenciasGenerales_CG property value.
     */
    boolean hasMA_otorgaCompetenciasGenerales_CG();
    /**
     * Adds a MA_otorgaCompetenciasGenerales_CG property value.<p>
     * 
     * @param newMA_otorgaCompetenciasGenerales_CG the MA_otorgaCompetenciasGenerales_CG property value to be added
     */
    void addMA_otorgaCompetenciasGenerales_CG(Competencia_General newMA_otorgaCompetenciasGenerales_CG);
    /**
     * Removes a MA_otorgaCompetenciasGenerales_CG property value.<p>
     * 
     * @param oldMA_otorgaCompetenciasGenerales_CG the MA_otorgaCompetenciasGenerales_CG property value to be removed.
     */
    void removeMA_otorgaCompetenciasGenerales_CG(Competencia_General oldMA_otorgaCompetenciasGenerales_CG);
    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_otorgaCompetencias_CO
     */
    /**
     * Gets all property values for the MA_otorgaCompetencias_CO property.<p>
     * 
     * @returns a collection of values for the MA_otorgaCompetencias_CO property.
     */
    Collection<? extends Competencia> getMA_otorgaCompetencias_CO();

    /**
     * Checks if the class has a MA_otorgaCompetencias_CO property value.<p>
     * 
     * @return true if there is a MA_otorgaCompetencias_CO property value.
     */
    boolean hasMA_otorgaCompetencias_CO();

    /**
     * Adds a MA_otorgaCompetencias_CO property value.<p>
     * 
     * @param newMA_otorgaCompetencias_CO the MA_otorgaCompetencias_CO property value to be added
     */
    void addMA_otorgaCompetencias_CO(Competencia newMA_otorgaCompetencias_CO);

    /**
     * Removes a MA_otorgaCompetencias_CO property value.<p>
     * 
     * @param oldMA_otorgaCompetencias_CO the MA_otorgaCompetencias_CO property value to be removed.
     */
    void removeMA_otorgaCompetencias_CO(Competencia oldMA_otorgaCompetencias_CO);


    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_seImparteMediante_ME
     */
     
    /**
     * Gets all property values for the MA_seImparteMediante_ME property.<p>
     * 
     * @returns a collection of values for the MA_seImparteMediante_ME property.
     */
    Collection<? extends Metodo_Docente> getMA_seImparteMediante_ME();

    /**
     * Checks if the class has a MA_seImparteMediante_ME property value.<p>
     * 
     * @return true if there is a MA_seImparteMediante_ME property value.
     */
    boolean hasMA_seImparteMediante_ME();

    /**
     * Adds a MA_seImparteMediante_ME property value.<p>
     * 
     * @param newMA_seImparteMediante_ME the MA_seImparteMediante_ME property value to be added
     */
    void addMA_seImparteMediante_ME(Metodo_Docente newMA_seImparteMediante_ME);

    /**
     * Removes a MA_seImparteMediante_ME property value.<p>
     * 
     * @param oldMA_seImparteMediante_ME the MA_seImparteMediante_ME property value to be removed.
     */
    void removeMA_seImparteMediante_ME(Metodo_Docente oldMA_seImparteMediante_ME);


    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_seImparteSegun_AF
     */
     
    /**
     * Gets all property values for the MA_seImparteSegun_AF property.<p>
     * 
     * @returns a collection of values for the MA_seImparteSegun_AF property.
     */
    Collection<? extends Actividad_Formativa> getMA_seImparteSegun_AF();

    /**
     * Checks if the class has a MA_seImparteSegun_AF property value.<p>
     * 
     * @return true if there is a MA_seImparteSegun_AF property value.
     */
    boolean hasMA_seImparteSegun_AF();

    /**
     * Adds a MA_seImparteSegun_AF property value.<p>
     * 
     * @param newMA_seImparteSegun_AF the MA_seImparteSegun_AF property value to be added
     */
    void addMA_seImparteSegun_AF(Actividad_Formativa newMA_seImparteSegun_AF);

    /**
     * Removes a MA_seImparteSegun_AF property value.<p>
     * 
     * @param oldMA_seImparteSegun_AF the MA_seImparteSegun_AF property value to be removed.
     */
    void removeMA_seImparteSegun_AF(Actividad_Formativa oldMA_seImparteSegun_AF);


    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_tiene_CA
     */
     
    /**
     * Gets all property values for the MA_tiene_CA property.<p>
     * 
     * @returns a collection of values for the MA_tiene_CA property.
     */
    Collection<? extends Caracter> getMA_tiene_CA();

    /**
     * Checks if the class has a MA_tiene_CA property value.<p>
     * 
     * @return true if there is a MA_tiene_CA property value.
     */
    boolean hasMA_tiene_CA();

    /**
     * Adds a MA_tiene_CA property value.<p>
     * 
     * @param newMA_tiene_CA the MA_tiene_CA property value to be added
     */
    void addMA_tiene_CA(Caracter newMA_tiene_CA);

    /**
     * Removes a MA_tiene_CA property value.<p>
     * 
     * @param oldMA_tiene_CA the MA_tiene_CA property value to be removed.
     */
    void removeMA_tiene_CA(Caracter oldMA_tiene_CA);


    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_ubicada_UT
     */
     
    /**
     * Gets all property values for the MA_ubicada_UT property.<p>
     * 
     * @returns a collection of values for the MA_ubicada_UT property.
     */
    Collection<? extends Ubicacion_temporal> getMA_ubicada_UT();

    /**
     * Checks if the class has a MA_ubicada_UT property value.<p>
     * 
     * @return true if there is a MA_ubicada_UT property value.
     */
    boolean hasMA_ubicada_UT();

    /**
     * Adds a MA_ubicada_UT property value.<p>
     * 
     * @param newMA_ubicada_UT the MA_ubicada_UT property value to be added
     */
    void addMA_ubicada_UT(Ubicacion_temporal newMA_ubicada_UT);

    /**
     * Removes a MA_ubicada_UT property value.<p>
     * 
     * @param oldMA_ubicada_UT the MA_ubicada_UT property value to be removed.
     */
    void removeMA_ubicada_UT(Ubicacion_temporal oldMA_ubicada_UT);


    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_utiliza_MV
     */
     
    /**
     * Gets all property values for the MA_utiliza_MV property.<p>
     * 
     * @returns a collection of values for the MA_utiliza_MV property.
     */
    Collection<? extends Metodo_Evaluacion> getMA_utiliza_MV();

    /**
     * Checks if the class has a MA_utiliza_MV property value.<p>
     * 
     * @return true if there is a MA_utiliza_MV property value.
     */
    boolean hasMA_utiliza_MV();

    /**
     * Adds a MA_utiliza_MV property value.<p>
     * 
     * @param newMA_utiliza_MV the MA_utiliza_MV property value to be added
     */
    void addMA_utiliza_MV(Metodo_Evaluacion newMA_utiliza_MV);

    /**
     * Removes a MA_utiliza_MV property value.<p>
     * 
     * @param oldMA_utiliza_MV the MA_utiliza_MV property value to be removed.
     */
    void removeMA_utiliza_MV(Metodo_Evaluacion oldMA_utiliza_MV);


    /* ***************************************************
     * Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * Gets all property values for the topObjectProperty property.<p>
     * 
     * @returns a collection of values for the topObjectProperty property.
     */
    Collection<? extends WrappedIndividual> getTopObjectProperty();

    /**
     * Checks if the class has a topObjectProperty property value.<p>
     * 
     * @return true if there is a topObjectProperty property value.
     */
    boolean hasTopObjectProperty();

    /**
     * Adds a topObjectProperty property value.<p>
     * 
     * @param newTopObjectProperty the topObjectProperty property value to be added
     */
    void addTopObjectProperty(WrappedIndividual newTopObjectProperty);

    /**
     * Removes a topObjectProperty property value.<p>
     * 
     * @param oldTopObjectProperty the topObjectProperty property value to be removed.
     */
    void removeTopObjectProperty(WrappedIndividual oldTopObjectProperty);


    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_Coordinacion
     */
     
    /**
     * Gets all property values for the MA_Coordinacion property.<p>
     * 
     * @returns a collection of values for the MA_Coordinacion property.
     */
    Collection<? extends String> getMA_Coordinacion();

    /**
     * Checks if the class has a MA_Coordinacion property value.<p>
     * 
     * @return true if there is a MA_Coordinacion property value.
     */
    boolean hasMA_Coordinacion();

    /**
     * Adds a MA_Coordinacion property value.<p>
     * 
     * @param newMA_Coordinacion the MA_Coordinacion property value to be added
     */
    void addMA_Coordinacion(String newMA_Coordinacion);

    /**
     * Removes a MA_Coordinacion property value.<p>
     * 
     * @param oldMA_Coordinacion the MA_Coordinacion property value to be removed.
     */
    void removeMA_Coordinacion(String oldMA_Coordinacion);



    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_Creditos
     */
     
    /**
     * Gets all property values for the MA_Creditos property.<p>
     * 
     * @returns a collection of values for the MA_Creditos property.
     */
    Collection<? extends Object> getMA_Creditos();

    /**
     * Checks if the class has a MA_Creditos property value.<p>
     * 
     * @return true if there is a MA_Creditos property value.
     */
    boolean hasMA_Creditos();

    /**
     * Adds a MA_Creditos property value.<p>
     * 
     * @param newMA_Creditos the MA_Creditos property value to be added
     */
    void addMA_Creditos(Object newMA_Creditos);

    /**
     * Removes a MA_Creditos property value.<p>
     * 
     * @param oldMA_Creditos the MA_Creditos property value to be removed.
     */
    void removeMA_Creditos(Object oldMA_Creditos);



    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/2011/10/Ontology1322242361907.owl#MA_Resultados
     */
     
    /**
     * Gets all property values for the MA_Resultados property.<p>
     * 
     * @returns a collection of values for the MA_Resultados property.
     */
    Collection<? extends String> getMA_Resultados();

    /**
     * Checks if the class has a MA_Resultados property value.<p>
     * 
     * @return true if there is a MA_Resultados property value.
     */
    boolean hasMA_Resultados();

    /**
     * Adds a MA_Resultados property value.<p>
     * 
     * @param newMA_Resultados the MA_Resultados property value to be added
     */
    void addMA_Resultados(String newMA_Resultados);

    /**
     * Removes a MA_Resultados property value.<p>
     * 
     * @param oldMA_Resultados the MA_Resultados property value to be removed.
     */
    void removeMA_Resultados(String oldMA_Resultados);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
