package TBox;
import java.util.Collection;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;
/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Materia <br>
 * @version generated on Tue Nov 12 01:41:05 CET 2013 by daniel
 */
public interface Materia extends WrappedIndividual {
    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#constaDe
     */
    /**
     * Gets all property values for the constaDe property.<p>
     * 
     * @returns a collection of values for the constaDe property.
     */
    Collection<? extends Asignatura> getConstaDe();
    /**
     * Checks if the class has a constaDe property value.<p>
     * 
     * @return true if there is a constaDe property value.
     */
    boolean hasConstaDe();
    /**
     * Adds a constaDe property value.<p>
     * 
     * @param newConstaDe the constaDe property value to be added
     */
    void addConstaDe(Asignatura newConstaDe);
    /**
     * Removes a constaDe property value.<p>
     * 
     * @param oldConstaDe the constaDe property value to be removed.
     */
    void removeConstaDe(Asignatura oldConstaDe);
    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#hereda
     */
     
    /**
     * Gets all property values for the hereda property.<p>
     * 
     * @returns a collection of values for the hereda property.
     */
    Collection<? extends Caracter> getHereda();

    /**
     * Checks if the class has a hereda property value.<p>
     * 
     * @return true if there is a hereda property value.
     */
    boolean hasHereda();

    /**
     * Adds a hereda property value.<p>
     * 
     * @param newHereda the hereda property value to be added
     */
    void addHereda(Caracter newHereda);

    /**
     * Removes a hereda property value.<p>
     * 
     * @param oldHereda the hereda property value to be removed.
     */
    void removeHereda(Caracter oldHereda);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#otorgaCompetenciaEspecifica
     */
     
    /**
     * Gets all property values for the otorgaCompetenciaEspecifica property.<p>
     * 
     * @returns a collection of values for the otorgaCompetenciaEspecifica property.
     */
    Collection<? extends Competencia_Especifica> getOtorgaCompetenciaEspecifica();

    /**
     * Checks if the class has a otorgaCompetenciaEspecifica property value.<p>
     * 
     * @return true if there is a otorgaCompetenciaEspecifica property value.
     */
    boolean hasOtorgaCompetenciaEspecifica();

    /**
     * Adds a otorgaCompetenciaEspecifica property value.<p>
     * 
     * @param newOtorgaCompetenciaEspecifica the otorgaCompetenciaEspecifica property value to be added
     */
    void addOtorgaCompetenciaEspecifica(Competencia_Especifica newOtorgaCompetenciaEspecifica);

    /**
     * Removes a otorgaCompetenciaEspecifica property value.<p>
     * 
     * @param oldOtorgaCompetenciaEspecifica the otorgaCompetenciaEspecifica property value to be removed.
     */
    void removeOtorgaCompetenciaEspecifica(Competencia_Especifica oldOtorgaCompetenciaEspecifica);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#otorgaCompetencias
     */
     
    /**
     * Gets all property values for the otorgaCompetencias property.<p>
     * 
     * @returns a collection of values for the otorgaCompetencias property.
     */
    Collection<? extends Competencia> getOtorgaCompetencias();

    /**
     * Checks if the class has a otorgaCompetencias property value.<p>
     * 
     * @return true if there is a otorgaCompetencias property value.
     */
    boolean hasOtorgaCompetencias();

    /**
     * Adds a otorgaCompetencias property value.<p>
     * 
     * @param newOtorgaCompetencias the otorgaCompetencias property value to be added
     */
    void addOtorgaCompetencias(Competencia newOtorgaCompetencias);

    /**
     * Removes a otorgaCompetencias property value.<p>
     * 
     * @param oldOtorgaCompetencias the otorgaCompetencias property value to be removed.
     */
    void removeOtorgaCompetencias(Competencia oldOtorgaCompetencias);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#otorgaCompetenciasGenerales
     */
     
    /**
     * Gets all property values for the otorgaCompetenciasGenerales property.<p>
     * 
     * @returns a collection of values for the otorgaCompetenciasGenerales property.
     */
    Collection<? extends Competencia_General> getOtorgaCompetenciasGenerales();

    /**
     * Checks if the class has a otorgaCompetenciasGenerales property value.<p>
     * 
     * @return true if there is a otorgaCompetenciasGenerales property value.
     */
    boolean hasOtorgaCompetenciasGenerales();

    /**
     * Adds a otorgaCompetenciasGenerales property value.<p>
     * 
     * @param newOtorgaCompetenciasGenerales the otorgaCompetenciasGenerales property value to be added
     */
    void addOtorgaCompetenciasGenerales(Competencia_General newOtorgaCompetenciasGenerales);

    /**
     * Removes a otorgaCompetenciasGenerales property value.<p>
     * 
     * @param oldOtorgaCompetenciasGenerales the otorgaCompetenciasGenerales property value to be removed.
     */
    void removeOtorgaCompetenciasGenerales(Competencia_General oldOtorgaCompetenciasGenerales);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#seEvaluaCon
     */
     
    /**
     * Gets all property values for the seEvaluaCon property.<p>
     * 
     * @returns a collection of values for the seEvaluaCon property.
     */
    Collection<? extends Metodo_Evaluacion> getSeEvaluaCon();

    /**
     * Checks if the class has a seEvaluaCon property value.<p>
     * 
     * @return true if there is a seEvaluaCon property value.
     */
    boolean hasSeEvaluaCon();

    /**
     * Adds a seEvaluaCon property value.<p>
     * 
     * @param newSeEvaluaCon the seEvaluaCon property value to be added
     */
    void addSeEvaluaCon(Metodo_Evaluacion newSeEvaluaCon);

    /**
     * Removes a seEvaluaCon property value.<p>
     * 
     * @param oldSeEvaluaCon the seEvaluaCon property value to be removed.
     */
    void removeSeEvaluaCon(Metodo_Evaluacion oldSeEvaluaCon);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#seImparteMediante
     */
     
    /**
     * Gets all property values for the seImparteMediante property.<p>
     * 
     * @returns a collection of values for the seImparteMediante property.
     */
    Collection<? extends Metodo_Docente> getSeImparteMediante();

    /**
     * Checks if the class has a seImparteMediante property value.<p>
     * 
     * @return true if there is a seImparteMediante property value.
     */
    boolean hasSeImparteMediante();

    /**
     * Adds a seImparteMediante property value.<p>
     * 
     * @param newSeImparteMediante the seImparteMediante property value to be added
     */
    void addSeImparteMediante(Metodo_Docente newSeImparteMediante);

    /**
     * Removes a seImparteMediante property value.<p>
     * 
     * @param oldSeImparteMediante the seImparteMediante property value to be removed.
     */
    void removeSeImparteMediante(Metodo_Docente oldSeImparteMediante);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#seImparteSegun
     */
     
    /**
     * Gets all property values for the seImparteSegun property.<p>
     * 
     * @returns a collection of values for the seImparteSegun property.
     */
    Collection<? extends Actividad_Formativa> getSeImparteSegun();

    /**
     * Checks if the class has a seImparteSegun property value.<p>
     * 
     * @return true if there is a seImparteSegun property value.
     */
    boolean hasSeImparteSegun();

    /**
     * Adds a seImparteSegun property value.<p>
     * 
     * @param newSeImparteSegun the seImparteSegun property value to be added
     */
    void addSeImparteSegun(Actividad_Formativa newSeImparteSegun);

    /**
     * Removes a seImparteSegun property value.<p>
     * 
     * @param oldSeImparteSegun the seImparteSegun property value to be removed.
     */
    void removeSeImparteSegun(Actividad_Formativa oldSeImparteSegun);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#ubicada
     */
     
    /**
     * Gets all property values for the ubicada property.<p>
     * 
     * @returns a collection of values for the ubicada property.
     */
    Collection<? extends Ubicacion_temporal> getUbicada();

    /**
     * Checks if the class has a ubicada property value.<p>
     * 
     * @return true if there is a ubicada property value.
     */
    boolean hasUbicada();

    /**
     * Adds a ubicada property value.<p>
     * 
     * @param newUbicada the ubicada property value to be added
     */
    void addUbicada(Ubicacion_temporal newUbicada);

    /**
     * Removes a ubicada property value.<p>
     * 
     * @param oldUbicada the ubicada property value to be removed.
     */
    void removeUbicada(Ubicacion_temporal oldUbicada);


    /* ***************************************************
     * Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * Gets all property values for the topObjectProperty property.<p>
     * 
     * @returns a collection of values for the topObjectProperty property.
     */
    Collection<? extends WrappedIndividual> getTopObjectProperty();

    /**
     * Checks if the class has a topObjectProperty property value.<p>
     * 
     * @return true if there is a topObjectProperty property value.
     */
    boolean hasTopObjectProperty();

    /**
     * Adds a topObjectProperty property value.<p>
     * 
     * @param newTopObjectProperty the topObjectProperty property value to be added
     */
    void addTopObjectProperty(WrappedIndividual newTopObjectProperty);

    /**
     * Removes a topObjectProperty property value.<p>
     * 
     * @param oldTopObjectProperty the topObjectProperty property value to be removed.
     */
    void removeTopObjectProperty(WrappedIndividual oldTopObjectProperty);


    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#coordinacionDeLaMateria
     */
     
    /**
     * Gets all property values for the coordinacionDeLaMateria property.<p>
     * 
     * @returns a collection of values for the coordinacionDeLaMateria property.
     */
    Collection<? extends String> getCoordinacionDeLaMateria();

    /**
     * Checks if the class has a coordinacionDeLaMateria property value.<p>
     * 
     * @return true if there is a coordinacionDeLaMateria property value.
     */
    boolean hasCoordinacionDeLaMateria();

    /**
     * Adds a coordinacionDeLaMateria property value.<p>
     * 
     * @param newCoordinacionDeLaMateria the coordinacionDeLaMateria property value to be added
     */
    void addCoordinacionDeLaMateria(String newCoordinacionDeLaMateria);

    /**
     * Removes a coordinacionDeLaMateria property value.<p>
     * 
     * @param oldCoordinacionDeLaMateria the coordinacionDeLaMateria property value to be removed.
     */
    void removeCoordinacionDeLaMateria(String oldCoordinacionDeLaMateria);



    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#creditosDeLaMateria
     */
     
    /**
     * Gets all property values for the creditosDeLaMateria property.<p>
     * 
     * @returns a collection of values for the creditosDeLaMateria property.
     */
    Collection<? extends Object> getCreditosDeLaMateria();

    /**
     * Checks if the class has a creditosDeLaMateria property value.<p>
     * 
     * @return true if there is a creditosDeLaMateria property value.
     */
    boolean hasCreditosDeLaMateria();

    /**
     * Adds a creditosDeLaMateria property value.<p>
     * 
     * @param newCreditosDeLaMateria the creditosDeLaMateria property value to be added
     */
    void addCreditosDeLaMateria(Object newCreditosDeLaMateria);

    /**
     * Removes a creditosDeLaMateria property value.<p>
     * 
     * @param oldCreditosDeLaMateria the creditosDeLaMateria property value to be removed.
     */
    void removeCreditosDeLaMateria(Object oldCreditosDeLaMateria);



    /* ***************************************************
     * Property http://www.semanticweb.org/daniel/Plan_Estudios#resultadosDelAprendizaje
     */
     
    /**
     * Gets all property values for the resultadosDelAprendizaje property.<p>
     * 
     * @returns a collection of values for the resultadosDelAprendizaje property.
     */
    Collection<? extends String> getResultadosDelAprendizaje();

    /**
     * Checks if the class has a resultadosDelAprendizaje property value.<p>
     * 
     * @return true if there is a resultadosDelAprendizaje property value.
     */
    boolean hasResultadosDelAprendizaje();

    /**
     * Adds a resultadosDelAprendizaje property value.<p>
     * 
     * @param newResultadosDelAprendizaje the resultadosDelAprendizaje property value to be added
     */
    void addResultadosDelAprendizaje(String newResultadosDelAprendizaje);

    /**
     * Removes a resultadosDelAprendizaje property value.<p>
     * 
     * @param oldResultadosDelAprendizaje the resultadosDelAprendizaje property value to be removed.
     */
    void removeResultadosDelAprendizaje(String oldResultadosDelAprendizaje);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
